[package]
name = "graphics-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
iced_wgpu = "0.13.5"
iced_widget = { version = "0.13.4", features = ["wgpu"] }
iced_winit = "0.13.0"
tracing-subscriber = "0.3.20"

[workspace]
resolver = "3"
members = ["parsers"]

